### ISSUE TITLE
Format of the FloatData Received by the Scorer from the FrontEnd in CMU Sphinx

### ISSUE THREAD

**Issue by mayankAshok** [cmusphinx/sphinx4#21]
We have been working on a project pertaining to Voice recognition and we are using Sphinx4 for the Digital Signal Processing phase. After analysing the code, we have seen that the FrontEnd module sends the output data to a Scorer. We discovered that given a sample configuration, after the FrontEnd voice processing is done, the scorer receives a list of FloatData with a float array. We wanted to know what each element in the array represents. It would be really useful if you could help us with it.

**Comment by nshmyrev** [comment]
You can learn a lot about speech recognition from the following book:

http://www.amazon.com/Spoken-Language-Processing-Algorithm-Development/dp/0130226165

**Comment by mayankAshok** [comment]
Thanks a lot. We'll get in touch if we have any more question.
