### ISSUE TITLE
Not able to run any demo

### ISSUE THREAD

**Issue by anupamme** [cmusphinx/sphinx4#23]
New to sphinx here. I am using java 1.7. 

I downloaded and opened the project in eclipse. But when I run any of the demo files e.g. edu.cmu.sphinx.demo.allphone.AllphoneDemo.java

I get a null pointer exception with following trace. I am using simple run as a java app in eclipse.

Exception in thread "main" java.lang.NullPointerException
	at edu.cmu.sphinx.util.props.SaxLoader.load(SaxLoader.java:71)
	at edu.cmu.sphinx.util.props.ConfigurationManager.<init>(ConfigurationManager.java:58)
	at edu.cmu.sphinx.api.Context.<init>(Context.java:59)
	at edu.cmu.sphinx.api.Context.<init>(Context.java:44)
	at edu.cmu.sphinx.demo.allphone.AllphoneDemo.main(AllphoneDemo.java:42)

Am I missing something here?

**Comment by nshmyrev** [comment]
Learn how to use maven

**Comment by anupamme** [comment]
I ran: "mvn2 install" on mac (new to maven as you guessed). But still getting the error. Are there any instructions on how to run a demo file.

**Comment by yingzong** [comment]
Ridiculous. Learn how to write docs. Idiots.

**Comment by timobaumann** [comment]
Hi anupamme. You are not reporting a bug but asking a question of how to get the software running. Please use the sphinx-4 forum for that next time. Regarding the problem that you have: how have you imported the project(s) into eclipse? Have you run mvn eclipse:eclipse to generate eclipse-.project files and imported the projects accordingly? Have you followed all relevant documentation (and if so, what have you done?).

**Comment by anupamme** [comment]
I am no longer working with sphinx. So thanks for the reply but I have 'moved on' since then. If I try again and run into issue will report in the forum.

This issue is closed. Thanks again!
