### ISSUE TITLE
problem running pocketsphinx_continuous

### ISSUE THREAD

**Issue by anupamme** [cmusphinx/sphinx4#24]
I built the pocketsphinx-5prealpha. And then I ran the following command:

./pocketsphinx_continuous -infile review2.mp3

I was expecting to get the speech to text output for review2.mp3 however I got longish output but nowhere it contains the text of the mp3 file

How do I achieve this: input the mp3/wav file and get output the text?

And is there is there a time limit on the length of the audio file?

**Comment by nshmyrev** [comment]
Pocketsphinx continuous takes only wav file 16khz 16bit mono files. To decode mp3 file you can convert it to wav with ffmpeg first:

       ffmpeg -i file.mp3 -ar 16000 -ac 1 file.wav
       pocketsphinx_continuous -infile file.wav
