### ISSUE TITLE
training the speech model

### ISSUE THREAD

**Issue by anupamme** [cmusphinx/sphinx4#25]
I am able to run the model but I am not getting good accuracy and I think since I have Indian english accent, this has a role to play in it.

So how can I train the model with my speech and text samples so that it better understands my accent?

I have downloaded sphinxtrain-5prealpha but I am clueless on how to use it to train the new model?

**Comment by nshmyrev** [comment]
This is sphinx4 repository on github, it is not related to training. To ask for help on cmusphinx you can use cmusphinx forums.
