### ISSUE TITLE
Impossible to instanciate awt.Robot

### ISSUE THREAD

**Issue by juxorevo** [cmusphinx/sphinx4#29]
I have also the same issue with the Sphinx4-5 (up to date). When I want to instantiate à Robot object. the program just do nothing on the instantiation line for Robot object, and doesn't continue the code. But the program is still running. I have no stacktrace because java just freeze. I think there is a conflict with internal java thread.

    public class HelloTest {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Configuration configuration = new Configuration();
		// Set path to acoustic model.
		configuration.setAcousticModelPath("resource:/edu/cmu/sphinx/models/en-us/en-us");
		// Set path to dictionary.
		configuration.setDictionaryPath("resource:/edu/cmu/sphinx/models/en-us/cmudict-en-us.dict");
		// Set language model.
		configuration.setLanguageModelPath("resource:/edu/cmu/sphinx/models/en-us/en-us.lm.dmp");
		
		LiveSpeechRecognizer recognizer = null;
		try {
			recognizer = new LiveSpeechRecognizer(configuration);
			// Start recognition process pruning previously cached data.
			recognizer.startRecognition(true);
			boolean trouve = true;
			
			Robot robot = new Robot();
			while(trouve){
				SpeechResult result = recognizer.getResult();
				System.out.println(result.getHypothesis());
			}

			// Pause recognition process. It can be resumed then with startRecognition(false).
			recognizer.stopRecognition();
		} catch (IOException | AWTException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

    }

I have also try to launch the Sphinx code in a thread, and the Robot code in an other thread. With this solution I have also the same problem.

I think the problem is with the thread "Java Sound Event Dispatcher" but I have no idea to solve it.

Precision : Without the line Robot rob = new Robot(); All work very fine.

Thank for reading.

**Comment by nshmyrev** [comment]
Sorry, this is an issue tracker. It is not the place to ask for help. You can ask for help on cmusphinx forum.

Before you ask, provide a full, complete and minimal code to reproduce your problem. Without code it is impossible to help you.
