### ISSUE TITLE
Maven build failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by aspratyush** [cmusphinx/sphinx4#32]
1) Maven build fails, and results in errors such as "error: enhanced for loops are not supported in -source 1.3"
2) The following patch resolves these errors and successfull build happens:

85,93d84
<       
<       <plugin>
<       	<groupId>org.apache.maven.plugins</groupId>
<       	<artifactId>maven-compiler-plugin</artifactId>
<       	<configuration>
<       		<source>1.6</source>
<       		<target>1.6</target>
<   		</configuration>
< 	  </plugin>
95c86
<     
---
>

**Comment by mbait** [comment]
I guess it's caused by aa4e1838f06eb032fd248601469b16ac95aeb08a, not sure why explicit version requirement has been removed. @aspratyush what you pasted is not a valid diff, but the problem is clear.

**Comment by aspratyush** [comment]
I didnt realize the formatting went for a toss.. forgot adding the backticks in the md..

```
85,93d84
<       
<       <plugin>
<       	<groupId>org.apache.maven.plugins</groupId>
<       	<artifactId>maven-compiler-plugin</artifactId>
<       	<configuration>
<       		<source>1.6</source>
<       		<target>1.6</target>
<   		</configuration>
< 	  </plugin>
95c86
<     
---
> 
```

**Comment by lmmx** [comment]
I got the same, also Ubu 14.04, and a MojoFailureException. Got past it by installing maven2, tried again without a failure. Looks like above comments may have resolved it but just mentioning in case it helps.

**Comment by nshmyrev** [comment]
Fixed, thanks a lot for the report.
