### ISSUE TITLE
Loading a previously saved Transform from a file in to Recognizer is not working.....

### ISSUE THREAD

**Issue by G10DRAS** [cmusphinx/sphinx4#40]
Using code from TranscriberDemo.java I successfully saved Transform in to a file as follows:

// Transform represents the speech profile
Transform transform = stats.createTransform();
transform.store("MyVoiceTransform", 0);

But when  I load Transform from file into the Recognizer, code didn't works. 
I debug the code and found issue with Scanner object in load() of Transform Class.
Scanner is not working as expected, ie not able to parse file. I use the following code to load Transform from file in to Recognizer.

StreamSpeechRecognizer recognizer = new StreamSpeechRecognizer(configuration);
recognizer.loadTransform("MyVoiceTransform", 1);

**Comment by G10DRAS** [comment]
Any update on the issue ?
Thanks in advance.

**Comment by nshmyrev** [comment]
Sorry, I didn't look yet. Thank you for the remainder.

**Comment by Arinerron** [comment]
I'm having the same issue. Any thoughts?

**Comment by G10DRAS** [comment]
Hello Nickolay,
Its a great feature, unfortunatly not working. 
Is there any thing equivalent to Transform Load, avalable that we can levarage, 
Thanks

**Comment by nshmyrev** [comment]
Hi

I actually fixed this probably in https://github.com/cmusphinx/sphinx4/commit/ffa62f865b258623926ed2bd23d5015570161c9d . I just need some more tests.

**Comment by G10DRAS** [comment]
Good news.
I will give it a try in a day or two.

Thank you Nickolay.

**Comment by Arinerron** [comment]
Yay, thanks :grinning:
