### ISSUE TITLE
gradle issue

### ISSUE THREAD

**Issue by luca-vercelli** [cmusphinx/sphinx4#42]
just downloaded, I cannot build:

    $ gradle

    FAILURE: Build failed with an exception.

    * Where:
    Build file '/home/luca/Documenti/src/sphinx/sphinx4/build.gradle' line: 13

    * What went wrong:
    A problem occurred evaluating root project 'sphinx4-parent'.
    > No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log     output.

    BUILD FAILED

    Total time: 4.539 secs

**Comment by nshmyrev** [comment]
Fixed, thank you for the report
