### ISSUE TITLE
Procedures to implement in Unity3D

### ISSUE THREAD

**Issue by Delaley** [cmusphinx/sphinx4#44]
Am stuck on a way to implement this in Unity3D. Any suggestions. Please is should be step by step.Thanks in Advance.

**Comment by mbait** [comment]
Are you asking for a fish? We only can teach people to fish, sorry.

**Comment by Delaley** [comment]
Yea I got yah. You see my problem is not knowing how to compile the source
but What packages do I need to include to make Speech to text work. I think
u get me right?

**Comment by mbait** [comment]
This library has nothing to do with Unity3D. I have a bare understanding of what Unity3D is (some kind of video game engine?). If you want to use sphinx4 with Unity - go ahead, let us know if you bump to any compilation or runtime problems. But here you are basically asking us to do your job for you.

**Comment by Delaley** [comment]
Kk no problem my bad. Not sure I would ask again. Coding gods forgive me.

**Comment by Delaley** [comment]
I think I've done enough. Lots of research and still no straight procedures to follow.  Am done u folks can keep your projects to yourselves. Am just wondering what harm would it cause you if one shows someone how stuffs work.
Goodbye see you latter

**Comment by SirWindfield** [comment]
Well, learning by doing I guess, try and error...

**Comment by Delaley** [comment]
You see I succesfully compiled Sphinx4 so my aim was to Use it as
multiplatform library since is jar. Simply my difficulty is what files do I
actually need.
After scooping the need I realized.
Most Android stuffs require package name. Looking at the Sphinx4 the
packages are way too much. So simply am confused as what package to import
to access the class.
So now u see my trouble.
