### ISSUE TITLE
automatically excluding edu/cmu/sphinx/decoder/search/

### ISSUE THREAD

**Issue by 7rabbit** [cmusphinx/sphinx4#48]
I try to download the repo and test. But when I start a java prj in eclipse some imports are automatically excluded. Is there any reason why? Thanks.

**Comment by nshmyrev** [comment]
It is not quite clear what do you mean by "excluded".

**Comment by 7rabbit** [comment]
Thanks for your response. It seems that some source folders are excluded to the build path in Eclipse when importing the whole project from Github. It leads to compile problem since some packages cannot be resolved.  
I solve the problem by creating my empty projects and linking .jar to my project. I just do not understand why clone from github does not work. It works for me with other previous repos. 
Thx!

**Comment by nshmyrev** [comment]
Ok, let me know if you have further questions
