### ISSUE TITLE
LiveSpeechRecognizer second start LineUnavailableException exception

### ISSUE THREAD

**Issue by troydm** [cmusphinx/sphinx4#57]
When using LiveSpeechRecognizer  I'm getting 

> javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.

when starting speech recognition second time after it has been stopped using stopRecognition method

**Comment by nshmyrev** [comment]
Duplicate of #33
