### ISSUE TITLE
How to use models given here https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/US%20English/

### ISSUE THREAD

**Issue by ivish** [cmusphinx/sphinx4#58]
I am having hard time to integrate models given here. I tried to integrate model cmusphinx-en-us-5.2 in pocketsphinx-5prealpha. Since this model is missing 'sendump' file.. I was getting error on running make.. 
Can I find some doc where I can understand the meaning of the files inside a model.
Thanks

**Comment by gorinars** [comment]
'sendump' is a compressed version of 'mixture_weights'

Check [here](http://cmusphinx.sourceforge.net/wiki/acousticmodelformat) for the acoustic model format.

Note that the model folder is not needed on 'make' stage. You compile pocketsphinx as usually and then specify the model folder in '-hmm' option. You may also find [this discussion](https://sourceforge.net/p/cmusphinx/discussion/help/thread/551963d1) useful.

If all above does not work, please post the command you run and the log file you get.

**Comment by ivish** [comment]
Thanks :) It helped

**Comment by gorinars** [comment]
You are welcome. Feel free to ask if there are other questions (and close this issue, as well)
