### ISSUE TITLE
Sometime aligner breaks and could not produce full json..please help

### ISSUE THREAD

**Issue by saquibajaz** [cmusphinx/sphinx4#60]

**Comment by nshmyrev** [comment]
It is not possible to help without details

**Comment by saquibajaz** [comment]
Don't recognized words after ~255 seconds:

... the(254.67,254.79) livingroom(254.79,255.29) and(255.29,2047.45)

**Comment by saquibajaz** [comment]
@nshmyrev.....i had provided the detail...now can you please help me

**Comment by nshmyrev** [comment]
You provided only one detail, you need to provide all necessary details.

**Comment by saquibajaz** [comment]
i had stated my problem with one detail..which is sufficient for understanding the problem..what other details you want..
