### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by leif81** [cmusphinx/sphinx4#62]
As far as I can tell, there aren't any official sphinx4 release artifacts in Maven Central, only unofficial forks.

http://search.maven.org/#search%7Cga%7C1%7Csphinx4

It'd be nice to have official artifacts published under the "edu.cmu.sphinx" group.

This would make it easy for developers to add Sphinx4 to their Maven projects, and use it with confidence that it's an official release.

**Comment by leif81** [comment]
I just noticed the `5prealpha` snapshots can be grabbed from sonatype snapshots repo.

http://cmusphinx.sourceforge.net/wiki/tutorialsphinx4

This is great. This is basically what I was looking for. I presume the 5.0 final release will get deployed to Maven Central.

**Comment by nshmyrev** [comment]
Correct
