### ISSUE TITLE
Sphinx4 LPC

### ISSUE THREAD

**Issue by andriiaveiro** [cmusphinx/sphinx4#67]
Sorry sphinx4 support lpc? How can i using lpc as a feature extraction? Please help me :(

**Comment by nshmyrev** [comment]
No, you have to use external library for conversion.

**Comment by andriiaveiro** [comment]
Thanks  for the fast reply and sorry for opening an issue for this question :( you have suggestion for external library? I just want get lpc coef in real time

**Comment by nshmyrev** [comment]
Something like http://jspeex.sourceforge.net should be good
