### ISSUE TITLE
NullPointerException in Lattice.java

### ISSUE THREAD

**Issue by tbook** [cmusphinx/sphinx4#68]
I've observed the following `NullPointerException` when calling `GetWords`:

    java.lang.NullPointerException
        at edu.cmu.sphinx.result.Lattice.getWordResultPath(Lattice.java:1062)
        at edu.cmu.sphinx.api.SpeechResult.getWords(SpeechResult.java:52)
        ...

It looks like `node.getWord()` sometimes returns null.  I haven't dug deep enough to see if that is intentional or not.

Using `5prealpha-SNAPSHOT` from `oss.sonatype.org`.

**Comment by nshmyrev** [comment]
Hi

Thanks for the report. Could you please provide at least some information to reproduce your problem?

**Comment by nshmyrev** [comment]
No information provided

**Comment by TomRK1089** [comment]
I've observed the same issue. It happens when I call `getWords()` on a `SpeechResult`.

For some WAV files, it's fine and I get the words, confidence, etc.
For others, it crashes.

It seems to be the same issue as: https://sourceforge.net/p/cmusphinx/discussion/sphinx4/thread/de04f6b3/
