### ISSUE TITLE
Index out of bounds exception after loading my own continous model 

### ISSUE THREAD

**Issue by romass12** [cmusphinx/sphinx4#78]
After training own continuous model on sphinx4,I get this error
![sphinx](https://user-images.githubusercontent.com/14347430/37950011-a89529f0-31b4-11e8-84e3-faf4df764f4d.jpg)
 During language model creation, using LMtool ,I get this:
![lm](https://user-images.githubusercontent.com/14347430/37950298-a82eee96-31b5-11e8-98ab-a2b3fa3def8d.jpg)

Kindly help

**Comment by nshmyrev** [comment]
Update sphinx4

**Comment by romass12** [comment]
I am using sphinx4 5realpha version

**Comment by nshmyrev** [comment]
Build from master

**Comment by romass12** [comment]
Can you help me in detail as to how to do that
