### ISSUE TITLE
Can we use this library for Speaker Identification? (Not the speaker diarization)

### ISSUE THREAD

**Issue by channae** [cmusphinx/sphinx4#81]
I need to train multiple speaker voice models and with a given audio input, Identify the correct speaker from the trained dataset. Basically I'm looking for clarification of speech between many people (but same language). Can we achieve speaker identification using this library? (I'm not looking for speaker diarization which labels the speaker rather speaker's name or an id using a pre-trained model).

**Comment by nshmyrev** [comment]
No it is not supported
