### ISSUE TITLE
Dictionary for en-70k-0.2-pruned language model

### ISSUE THREAD

**Issue by william-vw** [cmusphinx/sphinx4#89]
I know that I could try using `g2p-seq2seq` for constructing a dictionary based on the `en-70k-0.2-pruned` language model, but I was wondering whether one is already available. I cannot seem to find it on SourceForge or GitHub. When transcribing using the language model with the `cmudict` dictionary I get a range of errors saying "The dictionary is missing a phonetic transcription for the word ..".

**Comment by nshmyrev** [comment]
https://github.com/cmusphinx/sphinx4/blob/master/sphinx4-data/src/main/resources/edu/cmu/sphinx/models/en-us/cmudict-en-us.dict should work

**Comment by william-vw** [comment]
Sorry, it looks like it does! Don't know what went wrong before.
