### ISSUE TITLE
Infinite for loop bug

### ISSUE THREAD

**Issue by vlad-coteanu-uipath** [cmusphinx/sphinx4#99]
https://github.com/cmusphinx/sphinx4/blob/32df364ce3d9688c13a524981898931335d688e5/sphinx4-core/src/main/java/edu/cmu/sphinx/frontend/util/WavWriter.java#L221

Old:
for (int j = bytesPerValue - 1; j >= 0; j++) {
                byteArray[byteArInd + j] = (byte) (val & 0xff);
                val = val >> 8;
            }

Suggested:
for (int j = bytesPerValue - 1; j >= 0; j--) {
                byteArray[byteArInd + j] = (byte) (val & 0xff);
                val = val >> 8;
            }

**Comment by nshmyrev** [comment]
Fixed now with a pull request #100
